### ISSUE TITLE
CSRF token in a post call

### ISSUE THREAD

**Issue by mnkv1988** [jcailan/cdse#1]
Hi Jhodel,
When making a post call to a On-Prem destination, i can see two request in s/4 . CSRF token is perfectly requested and success , But this CSRF token is not in the real post call resulting in 403 error. Can you please check. Iam using latest version.

Regards,
Karthi

**Comment by jcailan** [comment]
Hi Karthi,
Published a fix - patch 1.0.7, let me know if it fixed your issue.
Thanks and regards,
Jhodel
